apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- Deployment.yml
- Namespace.yml
- Service.yml

secretGenerator:
  - name: promtest-secret
    env: .env


# generatorOptions:
#   disableNameSuffixHash: false